services:
  mcu-app:
    build: .
    container_name: mcu-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MAX_UPLOAD_FILES: 50
      MAX_UPLOAD_MB: 15
    volumes:
      - ./PDF FIle:/app/PDF FIle
      - ./PDF-backup:/app/PDF-backup
      - ./Excel File:/app/Excel File
